services:
  backend:
    image: node:lts
    working_dir: /home/node/app
    volumes:
      - ./backend:/home/node/app
      - /home/node/app/node_modules # exclude node_modules
    ports:
      - 3000:3000
    command: bash -c "npm i && npm run dev"

  frontend:
    image: node:lts
    working_dir: /home/node/app
    volumes:
      - ./frontend:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 5173:5173
    command: bash -c "npm i && npm run dev"
